CinemaABC/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('seats.urls')),
]

seats/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    MovieListView,
    seatSelect,
    orderSummary,
    orderComplete,
)

app_name = 'seats'

urlpatterns = [
    path('', MovieListView.as_view(), name="movie-list"),
    path('seat-select/<int:id>/', seatSelect, name="seat-select"),
    path('order-summary/', orderSummary, name="order-summary"),
    path('order-complete/', orderComplete, name="order-complete")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

seats/models.py
from django.db import models
from datetime import datetime as dt
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from django.utils import timezone


def upload_directory(instance, filename):
    """function to define where we want to upload an original image file
    Returns:
        uploads the file into the movieposters folder and subfolders with the current upload date
    """
    _now = dt.now()
    return 'movieposters/{year}/{month_date}/{filename}'.format(
        filename=filename, year=_now.strftime('%Y'), month_date=_now.strftime('%m%d')
    )


class Movie(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    year = models.CharField(max_length=4)
    duration = models.PositiveIntegerField(default=0)
    poster = models.ImageField(upload_to=upload_directory, blank=True, null=True,
                               validators=[FileExtensionValidator(
                                   allowed_extensions=['jpg', 'png'])]
                               )

    def __str__(self):
        return self.title


class CinemaHall(models.Model):
    hall_name = models.CharField(max_length=15, blank=True, null=True)
    row_length = models.PositiveSmallIntegerField(default=0)
    seats_length = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.hall_name


class ScreeningDate(models.Model):
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="dates")
    cinema_hall = models.ForeignKey(
        CinemaHall, on_delete=models.CASCADE, related_name="dates")
    screening_day = models.DateField()
    screening_hour = models.CharField(max_length=5)

    def __str__(self):
        return str(self.movie.title + ' , ' + str(self.screening_day) + ' , ' + str(self.screening_hour))

    class Meta:
        ordering = ['screening_day']

    # validation to prevent adding past screening date
    def save(self, *args, **kwargs):
        if self.screening_day < timezone.now().date():
            raise ValidationError("The date cannot be in the past!")
        super(ScreeningDate, self).save(*args, **kwargs)


class Seat(models.Model):
    cinema_hall = models.ForeignKey(
        CinemaHall, on_delete=models.CASCADE, related_name="seats")
    screening_date = models.ForeignKey(
        ScreeningDate, on_delete=models.CASCADE, related_name="seats")
    seat_number = models.PositiveSmallIntegerField(default=0)
    seat_sold = models.BooleanField(default=False)

    def __str__(self):
        return str(self.seat_number)

seats/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Movie, ScreeningDate, Seat
from django.http import HttpResponse
from .filters import MovieFilter
from django.utils import timezone


class MovieListView(ListView):
    """List all movies available  in cinema"""
    model = Movie

    def get_context_data(self, **kwargs):
        """"Changing the context data to apply the filter, and screening date validation
        """
        context = super(MovieListView, self).get_context_data(**kwargs)

        # Film screenings that have taken place already are being removed
        qs = Movie.objects.all()
        for movie in qs:
            if movie.dates:
                dates = ScreeningDate.objects.filter(movie=movie)
                for date in dates:
                    if date.screening_day < timezone.now().date():
                        date.delete()

        context['filter'] = MovieFilter(
            self.request.GET, queryset=Movie.objects.all())
        return context


def seatSelect(request, id):
    """function to display and select seats in the cinema room
    """
    context = {}
    screening_date = ScreeningDate.objects.get(id=id)
    cinema_hall = screening_date.cinema_hall

    # create our own cinema hall with the number of seats and rows (in Model CinemaHall)
    rows = [_ for _ in range(1, cinema_hall.row_length+1)]
    seats_length = [_ for _ in range(1, cinema_hall.seats_length+1)]

    # sending the list of sold seats to template (then js marks them as sold)
    sold_seats = []
    sold = screening_date.seats.all()
    for obj in sold:
        sold_seats.append(obj.seat_number)
    sold_seats = list(map(str, sold_seats))

    context['sold_seats'] = sold_seats
    context['rows'] = rows
    context['seats_length'] = seats_length
    context['date'] = screening_date

    return render(request, 'seat_list.html', context)


def orderSummary(request):
    """simple function to display summary template
    """
    context = {}
    seat_selected = request.GET.getlist('seat_list[]')
    screening_date_id = request.GET.get('screening_date')

    screening_date = ScreeningDate.objects.get(id=screening_date_id)

    context['screening_date'] = screening_date
    context['seat_list'] = seat_selected

    return render(request, 'summary_list.html', context)


def orderComplete(request):
    """function to order seats, and display booking confirmation
    """
    context = {}
    seat_selected = request.GET.getlist('seat_list[]')
    screening_date_id = request.GET.get('screening_date')

    screening_date = ScreeningDate.objects.get(id=screening_date_id)

    context['screening_date'] = screening_date
    context['seat_list'] = seat_selected

    # book seat but first checking if seat isn't already booked(its handle by js, but in a case of front error additional validation in backend)
    if seat_selected:
        for seat_number in seat_selected:
            qs = Seat.objects.filter(
                seat_number=seat_number, screening_date=screening_date)
            if qs.exists():
                return HttpResponse({'ERROR: Something wrong, seats already booked..'})
            else:
                seat = Seat.objects.create(
                    screening_date=screening_date,
                    cinema_hall=screening_date.cinema_hall,
                    seat_number=seat_number,
                    seat_sold=True,
                )
                seat.save()

    return render(request, 'order_complete.html', context)

templates/order_complete.html
<body>

<body>
  <div class="container">
        <a href="{% url 'seats:seat-select' screening_date.id %}" class="text-light"><i class="fa-solid fa-left-long"></i> Back to cinema hall view</a>
        <h2 class="screening_date text-light" id="{{screening_date.id}}">Order successful ! </h2>

        <h4 style="margin: 3px;">Order successful on show: {{screening_date}}</h4>
        <h4>Your show will be on cinema hall number: {{screening_date.cinema_hall}} </h4>
        <h3>Your seat numbers: {% for seat in seat_list %}{{seat}} , {% endfor %}</h3>
  </div>
</body>

templates/seat_list.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/main.css' %}" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">


<body>

  <div class="movie-container">
    <span><a href="{% url 'seats:movie-list' %}" style="color: white;"><i class="fa-solid fa-left-long"></i> Back to home page</a><span></span>
    <div class="screening_date" id="{{date.id}}">
      <h3>{{date}}</h3>
    </div>
      <h5>Cinema Hall number: {{ date.cinema_hall }}</h5>
    </span>
  </div>

  <ul class="showcase">
    <li>
      <div class="show-seat"></div>
      <small>Available</small>
    </li>
    <li>
      <div class="show-seat selected"></div>
      <small>Selected</small>
    </li>
    <li>
      <div class="show-seat sold"></div>
      <small>Sold</small>
    </li>
  </ul>
  <div class="container">
    <div class="screen"></div>


      <div class="container">
        <div class="row">
          Seat:
        {% for seat in seats_length %}
              <div class="seat-row"> {{seat}}</div>
        {% endfor %}
        </div>
          {% for row in rows %}
          <div class="row">
            <span> R. {{ row }}  </span>
            {% for seat in seats_length %}
              <div class="seat" name="seat" id="{{row}}{{seat}}" ></div>
            {% endfor %}
          </div>
          {% endfor %}

        </div>
  </div>


  <div class="container">
    You have selected <span id="count">0</span> seats.
  </div>
  <button type="submit" id="summary-btn" class="summary-btn" >Order selected seats</button>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'scripts.js' %}"></script>
<script src="{% static 'backend.js' %}"></script>

<script>

var soldSeats = {{ sold_seats|safe }}
var allSeats = document.getElementsByClassName("seat");

for (let seat of allSeats) {
    if (soldSeats.includes(seat.id)){
      seat.classList.add('sold')
  }
}

</script>

</body>

templates/seats/movie_list.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Krzysztof Kuta">
    <title>Cinema reservation system</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    <style>
      body {
        background-color: #242333;
      }
      .img-fluid {
        max-width: 100%;
        height: auto;
      }
    </style>


  </head>
<body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Cinema reservation</h4>
          <p class="text-muted">Simple quick system of booking seats in the cinema, the ability to choose a film from the current repertoire for the day, and the choice of available unreserved seats</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">My portfolio GITHUB</a></li>
            <li><a href="#" class="text-white">LinkedIn</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Cinema ABC</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

  <section class="py-3 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light text-white">Welcome to Cinema ABC</h1>
        <p class="lead text-muted">Choose a movie from our repertoire, book a seat and enjoy super fun for the whole family</p>
      </div>
    </div>
  </section>

  <div class="album">
    <div class="container">
      <div class="filterSection mb-3 text-light">

        <label for="movieFilter">Filter by movie</label>
        <select name="movieFilter" id="movieFilter" class="form-control">
          <option value="" disabled selected>Select movie</option>
          {% for movie in object_list %}
          <option name="movieFilterOption" value="{{ movie }}">{{ movie }}</option>
          {% endfor %}
        </select>
        <a href="/" class="text-light">Clear filters</a>
      </div>

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for movie in filter.qs %}
            <div class="col">
              <div class="card shadow-sm text-center">
                <h2>{{movie}}</h2>
                {% if movie.poster %}
                <img src="{{ movie.poster.url }}" class="img-fluid rounded" width="100%" height="100%">
                {% endif %}
                <div class="card-body">
                  <p class="card-text">{{ movie.description }}</p>
                  <small class="text-muted">Duration: {{ movie.duration }} mins</small>
                  <p></p>
                  {% if movie.dates.all.count >= 1 %}
                    {% for date in movie.dates.all|slice:":1" %}
                        <p>Upcoming screening:</p>
                        <p><a name="screening_hour" style="color: green;"  href="{% url 'seats:seat-select' date.id %}">{{ date.screening_day }} - {{ date.screening_hour }}</a></p>

                        <!-- Button trigger modal -->
                        <div class="btn-group">
                          <button type="button" data-bs-toggle="modal" data-bs-target="#screening_{{ date.id }}" class="btn btn-sm btn-outline-secondary">Show more screening dates</button>
                        </div>

                        <!-- Modal -->
                        <div class="modal fade" id="screening_{{ date.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">{{ movie }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-body">
                                {% for date in movie.dates.all %}
                                  <p><a name="screening_hour" style="color: green;"  href="{% url 'seats:seat-select' date.id %}">{{ date.screening_day }} - {{ date.screening_hour }}</a></p>
                                {% endfor %}
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>
                    {% endfor %}
                  {% else %}
                  <div class="d-flex justify-content-center align-items-center">
                    <div class="btn-group">
                        <div class="btn-sm btn-outline-secondary">There is no screening now!</div>
                    </div>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
        {% endfor %}
      </div>
    </div>
  </div>


<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">2022 Cinema ABC - online reservation system.</p>
  </div>
</footer>

</body>

<script>
let movieFilter = document.getElementById('movieFilter')

movieFilter.addEventListener('change',(e)=>{
  let movieFilterVal = e.target.value
  let params = new window.URLSearchParams(window.location.search);
  params.set('title', movieFilterVal);
  let paramsURL = params.toString();
  let urlToChange = "?" + paramsURL;
  window.history.pushState({}, document.title, urlToChange );
  location.reload()
})

var myModal = document.getElementById('myModal')
var myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', function () {
  myInput.focus()
})
</script>
</html>

templates/seats/summary_list.html

<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>



<style>
  @import url("https://fonts.googleapis.com/css?family=Lato&display=swap");

* {
  box-sizing: border-box;
}

body {
  background-color: #242333;
  color: #242333;
  display: flex;
  flex-direction: column;
  align-items: top;
  justify-content: top;
  height: 100vh;
  font-family: "Lato", sans-serif;
  margin: 50px;
}

</style>


<body>
  <div class="container">
        <a href="" class="text-light"><i class="fa-solid fa-left-long"></i> Back to seats</a>
        <h2 class="text-light">Order Summary</h2>
        <table class="table">
          <thead>
            <tr class="text-light">
              <th scope="col">#</th>
              <th scope="col">Movie title</th>
              <th scope="col">Date</th>
              <th scope="col">Hour</th>
              <th scope="col">Seat number</th>
              <th scope="col">Price</th>

            </tr>
          </thead>
      </div>

</body>

templates/summary_list.html

<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>



<style>
  @import url("https://fonts.googleapis.com/css?family=Lato&display=swap");

* {
  box-sizing: border-box;
}

body {
  background-color: #242333;
  color: #242333;
  display: flex;
  flex-direction: column;
  align-items: top;
  justify-content: top;
  height: 100vh;
  font-family: "Lato", sans-serif;
  margin: 50px;
}

</style>


<body>
  <div class="container">
        <a href="" class="text-light"><i class="fa-solid fa-left-long"></i> Back to seats</a>
        <h2 class="screening_date text-light" id="{{screening_date.id}}">Order Summary - {{screening_date}}</h2>
        <table class="table">
          <thead>
            <tr class="text-light">
              <th scope="col">#</th>
              <th scope="col">Movie title</th>
              <th scope="col">Date</th>
              <th scope="col">Hour</th>
              <th scope="col">Seat number</th>
              <th scope="col">Price</th>

            </tr>
          </thead>
          <tbody>
          {% if seat_list %}
              {% for seat in seat_list %}
                <tr class="text-light">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ screening_date.movie }}</td>
                    <td>{{ screening_date.screening_day }}</td>
                    <td>{{ screening_date.screening_hour }}</td>
                    <td><div class="selected-seat" id="{{seat}}">{{ seat }}</div></td>
                    <td>0$</td>
                </tr>
              {% endfor %}
            {% else %}
            <tr>
              <td  class="text-light" colspan="5">Your cart is empty</td>
            </tr>
            {% endif %}

          </tbody>
        </table>
                <input type="text" name="seats" id="seats" hidden>

              <td colspan="5">
                <a class='order-seats btn btn-warning float-right ml-2' type="submit">Make reservation</a>

              </td>
                <a class='btn btn-primary float-right' href="/">Check another movie</a>

  </div>

</body>